// Firebase config + hằng số game
const firebaseConfig = {
  apiKey: "AIzaSyC96Hq3bgVbCIff95AOp1epL-8ho3_Ukqk",
  authDomain: "trongcay-b417b.firebaseapp.com",
  databaseURL: "https://trongcay-b417b-default-rtdb.asia-southeast1.firebasedatabase.app",
  projectId: "trongcay-b417b",
  storageBucket: "trongcay-b417b.firebasestorage.app",
  messagingSenderId: "642266531520",
  appId: "1:642266531520:web:d71cb8bce7cacd2263cf25",
  measurementId: "G-FJB0W8W8D2"
};

const AVATARS = ['🌿','🌳','🌴','🌵','🌸','🍀','🌻','🍃','🪴','🌲','🎋','🌹','🍋','🍎','🌺','🌼'];

const TREE_TYPES = [
  { id:'basic', name:'Cây thường', emoji:['🌱','🌿','🪴','🌳','🌲','🌴','🏞️'], unlock:0, eventOnly:false },
  { id:'fruit', name:'Cây ăn quả', emoji:['🌱','🌿','🪴','🍋','🍊','🍎','🍎'], unlock:5, eventOnly:false },
  { id:'flower', name:'Cây hoa', emoji:['🌱','🌿','🌷','🌸','🌺','🌹','💐'], unlock:10, eventOnly:false },
  { id:'cactus', name:'Xương rồng', emoji:['🌵','🌵','🌵','🌵','🌵','🌵','🌵'], unlock:15, eventOnly:false },
  { id:'bamboo', name:'Tre', emoji:['🌱','🎋','🎋','🎍','🎍','🎍','🎍'], unlock:20, eventOnly:false },
  { id:'sakura', name:'Hoa anh đào', emoji:['🌱','🌿','🌷','🌸','🌺','🌹','💐'], unlock:30, eventOnly:false },
  { id:'event_lantern', name:'Cây đèn lồng', emoji:['🌱','🌿','🪴','🌳','🌲','🌴','🏞️'], unlock:999, eventOnly:true },
  { id:'tree_001', name:'Cây Tùng', emoji:['🌱','🌿','🪴','🌳','🌲','🌴','🏞️'], unlock:3, eventOnly:false },
  { id:'tree_002', name:'Cây Bách', emoji:['🌱','🌿','🪴','🍋','🍊','🍎','🍎'], unlock:4, eventOnly:false },
  { id:'tree_003', name:'Cây Phượng', emoji:['🌱','🌿','🌷','🌸','🌺','🌹','💐'], unlock:5, eventOnly:false },
  { id:'tree_004', name:'Cây Lim', emoji:['🌵','🌵','🌵','🌵','🌵','🌵','🌵'], unlock:6, eventOnly:false },
  { id:'tree_005', name:'Cây Gụ', emoji:['🌱','🎋','🎋','🎍','🎍','🎍','🎍'], unlock:7, eventOnly:false },
  { id:'tree_006', name:'Cây Sến', emoji:['🌱','🌿','🌴','🌴','🌴','🏝️','🏝️'], unlock:8, eventOnly:false },
  { id:'tree_007', name:'Cây Táu', emoji:['🍄','🍄','🍄','🍄','🍄','🍄','🍄'], unlock:9, eventOnly:false },
  { id:'tree_008', name:'Cây Dầu', emoji:['🌱','🌿','🥬','🥗','🥦','🥒','🥒'], unlock:10, eventOnly:false },
  { id:'tree_009', name:'Cây Sao', emoji:['🌱','🌿','🫐','🫐','🍇','🍇','🍇'], unlock:11, eventOnly:false },
  { id:'tree_010', name:'Cây Tràm', emoji:['🌱','🌿','🍒','🍒','🍒','🌳','🏞️'], unlock:12, eventOnly:false },
  { id:'tree_011', name:'Cây Keo', emoji:['🌱','🌿','🪴','🌳','🌲','🌴','🏞️'], unlock:13, eventOnly:false },
  { id:'tree_012', name:'Cây Bạch đàn', emoji:['🌱','🌿','🪴','🍋','🍊','🍎','🍎'], unlock:14, eventOnly:false },
  { id:'tree_013', name:'Cây Xoài', emoji:['🌱','🌿','🌷','🌸','🌺','🌹','💐'], unlock:15, eventOnly:false },
  { id:'tree_014', name:'Cây Nhãn', emoji:['🌵','🌵','🌵','🌵','🌵','🌵','🌵'], unlock:16, eventOnly:false },
  { id:'tree_015', name:'Cây Vải', emoji:['🌱','🎋','🎋','🎍','🎍','🎍','🎍'], unlock:17, eventOnly:false },
  { id:'tree_016', name:'Cây Sầu riêng', emoji:['🌱','🌿','🌴','🌴','🌴','🏝️','🏝️'], unlock:18, eventOnly:false },
  { id:'tree_017', name:'Cây Mít', emoji:['🍄','🍄','🍄','🍄','🍄','🍄','🍄'], unlock:19, eventOnly:false },
  { id:'tree_018', name:'Cây Ổi', emoji:['🌱','🌿','🥬','🥗','🥦','🥒','🥒'], unlock:20, eventOnly:false },
  { id:'tree_019', name:'Cây Đu đủ', emoji:['🌱','🌿','🫐','🫐','🍇','🍇','🍇'], unlock:21, eventOnly:false },
  { id:'tree_020', name:'Cây Chuối', emoji:['🌱','🌿','🍒','🍒','🍒','🌳','🏞️'], unlock:22, eventOnly:false },
  { id:'tree_021', name:'Cây Dừa', emoji:['🌱','🌿','🪴','🌳','🌲','🌴','🏞️'], unlock:23, eventOnly:false },
  { id:'tree_022', name:'Cây Cau', emoji:['🌱','🌿','🪴','🍋','🍊','🍎','🍎'], unlock:24, eventOnly:false },
  { id:'tree_023', name:'Cây Trầu', emoji:['🌱','🌿','🌷','🌸','🌺','🌹','💐'], unlock:25, eventOnly:false },
  { id:'tree_024', name:'Cây Chè', emoji:['🌵','🌵','🌵','🌵','🌵','🌵','🌵'], unlock:26, eventOnly:false },
  { id:'tree_025', name:'Cây Cà phê', emoji:['🌱','🎋','🎋','🎍','🎍','🎍','🎍'], unlock:27, eventOnly:false },
  { id:'tree_026', name:'Cây Ca cao', emoji:['🌱','🌿','🌴','🌴','🌴','🏝️','🏝️'], unlock:28, eventOnly:false },
  { id:'tree_027', name:'Cây Hồ tiêu', emoji:['🍄','🍄','🍄','🍄','🍄','🍄','🍄'], unlock:29, eventOnly:false },
  { id:'tree_028', name:'Cây Điều', emoji:['🌱','🌿','🥬','🥗','🥦','🥒','🥒'], unlock:30, eventOnly:false },
  { id:'tree_029', name:'Cây Macca', emoji:['🌱','🌿','🫐','🫐','🍇','🍇','🍇'], unlock:31, eventOnly:false },
  { id:'tree_030', name:'Cây Bơ', emoji:['🌱','🌿','🍒','🍒','🍒','🌳','🏞️'], unlock:32, eventOnly:false },
  { id:'tree_031', name:'Cây Cam', emoji:['🌱','🌿','🪴','🌳','🌲','🌴','🏞️'], unlock:33, eventOnly:false },
  { id:'tree_032', name:'Cây Quýt', emoji:['🌱','🌿','🪴','🍋','🍊','🍎','🍎'], unlock:34, eventOnly:false },
  { id:'tree_033', name:'Cây Bưởi', emoji:['🌱','🌿','🌷','🌸','🌺','🌹','💐'], unlock:35, eventOnly:false },
  { id:'tree_034', name:'Cây Chanh', emoji:['🌵','🌵','🌵','🌵','🌵','🌵','🌵'], unlock:36, eventOnly:false },
  { id:'tree_035', name:'Cây Kiwi', emoji:['🌱','🎋','🎋','🎍','🎍','🎍','🎍'], unlock:37, eventOnly:false },
  { id:'tree_036', name:'Cây Dâu tây', emoji:['🌱','🌿','🌴','🌴','🌴','🏝️','🏝️'], unlock:38, eventOnly:false },
  { id:'tree_037', name:'Cây Mâm xôi', emoji:['🍄','🍄','🍄','🍄','🍄','🍄','🍄'], unlock:39, eventOnly:false },
  { id:'tree_038', name:'Cây Việt quất', emoji:['🌱','🌿','🥬','🥗','🥦','🥒','🥒'], unlock:40, eventOnly:false },
  { id:'tree_039', name:'Cây Nho', emoji:['🌱','🌿','🫐','🫐','🍇','🍇','🍇'], unlock:41, eventOnly:false },
  { id:'tree_040', name:'Cây Lựu', emoji:['🌱','🌿','🍒','🍒','🍒','🌳','🏞️'], unlock:42, eventOnly:false },
  { id:'tree_041', name:'Cây Đào', emoji:['🌱','🌿','🪴','🌳','🌲','🌴','🏞️'], unlock:3, eventOnly:false },
  { id:'tree_042', name:'Cây Lê', emoji:['🌱','🌿','🪴','🍋','🍊','🍎','🍎'], unlock:4, eventOnly:false },
  { id:'tree_043', name:'Cây Táo', emoji:['🌱','🌿','🌷','🌸','🌺','🌹','💐'], unlock:5, eventOnly:false },
  { id:'tree_044', name:'Cây Mận', emoji:['🌵','🌵','🌵','🌵','🌵','🌵','🌵'], unlock:6, eventOnly:false },
  { id:'tree_045', name:'Cây Mơ', emoji:['🌱','🎋','🎋','🎍','🎍','🎍','🎍'], unlock:7, eventOnly:false },
  { id:'tree_046', name:'Cây Anh đào', emoji:['🌱','🌿','🌴','🌴','🌴','🏝️','🏝️'], unlock:8, eventOnly:false },
  { id:'tree_047', name:'Cây Hạnh', emoji:['🍄','🍄','🍄','🍄','🍄','🍄','🍄'], unlock:9, eventOnly:false },
  { id:'tree_048', name:'Cây Óc chó', emoji:['🌱','🌿','🥬','🥗','🥦','🥒','🥒'], unlock:10, eventOnly:false },
  { id:'tree_049', name:'Cây Hạt dẻ', emoji:['🌱','🌿','🫐','🫐','🍇','🍇','🍇'], unlock:11, eventOnly:false },
  { id:'tree_050', name:'Cây Hạt điều', emoji:['🌱','🌿','🍒','🍒','🍒','🌳','🏞️'], unlock:12, eventOnly:false },
  { id:'tree_051', name:'Cây Hướng dương', emoji:['🌱','🌿','🪴','🌳','🌲','🌴','🏞️'], unlock:13, eventOnly:false },
  { id:'tree_052', name:'Cây Cúc', emoji:['🌱','🌿','🪴','🍋','🍊','🍎','🍎'], unlock:14, eventOnly:false },
  { id:'tree_053', name:'Cây Hồng', emoji:['🌱','🌿','🌷','🌸','🌺','🌹','💐'], unlock:15, eventOnly:false },
  { id:'tree_054', name:'Cây Lan', emoji:['🌵','🌵','🌵','🌵','🌵','🌵','🌵'], unlock:16, eventOnly:false },
  { id:'tree_055', name:'Cây Huệ', emoji:['🌱','🎋','🎋','🎍','🎍','🎍','🎍'], unlock:17, eventOnly:false },
  { id:'tree_056', name:'Cây Lay ơn', emoji:['🌱','🌿','🌴','🌴','🌴','🏝️','🏝️'], unlock:18, eventOnly:false },
  { id:'tree_057', name:'Cây Thược dược', emoji:['🍄','🍄','🍄','🍄','🍄','🍄','🍄'], unlock:19, eventOnly:false },
  { id:'tree_058', name:'Cây Cẩm tú cầu', emoji:['🌱','🌿','🥬','🥗','🥦','🥒','🥒'], unlock:20, eventOnly:false },
  { id:'tree_059', name:'Cây Tường vi', emoji:['🌱','🌿','🫐','🫐','🍇','🍇','🍇'], unlock:21, eventOnly:false },
  { id:'tree_060', name:'Cây Nhài', emoji:['🌱','🌿','🍒','🍒','🍒','🌳','🏞️'], unlock:22, eventOnly:false },
  { id:'tree_061', name:'Cây Lài', emoji:['🌱','🌿','🪴','🌳','🌲','🌴','🏞️'], unlock:23, eventOnly:false },
  { id:'tree_062', name:'Cây Mộc', emoji:['🌱','🌿','🪴','🍋','🍊','🍎','🍎'], unlock:24, eventOnly:false },
  { id:'tree_063', name:'Cây Ngọc lan', emoji:['🌱','🌿','🌷','🌸','🌺','🌹','💐'], unlock:25, eventOnly:false },
  { id:'tree_064', name:'Cây Sứ', emoji:['🌵','🌵','🌵','🌵','🌵','🌵','🌵'], unlock:26, eventOnly:false },
  { id:'tree_065', name:'Cây Đại', emoji:['🌱','🎋','🎋','🎍','🎍','🎍','🎍'], unlock:27, eventOnly:false },
  { id:'tree_066', name:'Cây Phong lan', emoji:['🌱','🌿','🌴','🌴','🌴','🏝️','🏝️'], unlock:28, eventOnly:false },
  { id:'tree_067', name:'Cây Sen', emoji:['🍄','🍄','🍄','🍄','🍄','🍄','🍄'], unlock:29, eventOnly:false },
  { id:'tree_068', name:'Cây Súng', emoji:['🌱','🌿','🥬','🥗','🥦','🥒','🥒'], unlock:30, eventOnly:false },
  { id:'tree_069', name:'Cây Lúa', emoji:['🌱','🌿','🫐','🫐','🍇','🍇','🍇'], unlock:31, eventOnly:false },
  { id:'tree_070', name:'Cây Ngô', emoji:['🌱','🌿','🍒','🍒','🍒','🌳','🏞️'], unlock:32, eventOnly:false },
  { id:'tree_071', name:'Cây Lúa mì', emoji:['🌱','🌿','🪴','🌳','🌲','🌴','🏞️'], unlock:33, eventOnly:false },
  { id:'tree_072', name:'Cây Khoai', emoji:['🌱','🌿','🪴','🍋','🍊','🍎','🍎'], unlock:34, eventOnly:false },
  { id:'tree_073', name:'Cây Sắn', emoji:['🌱','🌿','🌷','🌸','🌺','🌹','💐'], unlock:35, eventOnly:false },
  { id:'tree_074', name:'Cây Khoai lang', emoji:['🌵','🌵','🌵','🌵','🌵','🌵','🌵'], unlock:36, eventOnly:false },
  { id:'tree_075', name:'Cây Cà chua', emoji:['🌱','🎋','🎋','🎍','🎍','🎍','🎍'], unlock:37, eventOnly:false },
  { id:'tree_076', name:'Cây Ớt', emoji:['🌱','🌿','🌴','🌴','🌴','🏝️','🏝️'], unlock:38, eventOnly:false },
  { id:'tree_077', name:'Cây Dưa leo', emoji:['🍄','🍄','🍄','🍄','🍄','🍄','🍄'], unlock:39, eventOnly:false },
  { id:'tree_078', name:'Cây Bí', emoji:['🌱','🌿','🥬','🥗','🥦','🥒','🥒'], unlock:40, eventOnly:false },
  { id:'tree_079', name:'Cây Bầu', emoji:['🌱','🌿','🫐','🫐','🍇','🍇','🍇'], unlock:41, eventOnly:false },
  { id:'tree_080', name:'Cây Mướp', emoji:['🌱','🌿','🍒','🍒','🍒','🌳','🏞️'], unlock:42, eventOnly:false },
  { id:'tree_081', name:'Cây Rau muống', emoji:['🌱','🌿','🪴','🌳','🌲','🌴','🏞️'], unlock:3, eventOnly:false },
  { id:'tree_082', name:'Cây Rau cải', emoji:['🌱','🌿','🪴','🍋','🍊','🍎','🍎'], unlock:4, eventOnly:false },
  { id:'tree_083', name:'Cây Xà lách', emoji:['🌱','🌿','🌷','🌸','🌺','🌹','💐'], unlock:5, eventOnly:false },
  { id:'tree_084', name:'Cây Cải thìa', emoji:['🌵','🌵','🌵','🌵','🌵','🌵','🌵'], unlock:6, eventOnly:false },
  { id:'tree_085', name:'Cây Bạc hà', emoji:['🌱','🎋','🎋','🎍','🎍','🎍','🎍'], unlock:7, eventOnly:false },
  { id:'tree_086', name:'Cây Húng', emoji:['🌱','🌿','🌴','🌴','🌴','🏝️','🏝️'], unlock:8, eventOnly:false },
  { id:'tree_087', name:'Cây Rau thơm', emoji:['🍄','🍄','🍄','🍄','🍄','🍄','🍄'], unlock:9, eventOnly:false },
  { id:'tree_088', name:'Cây Ngò', emoji:['🌱','🌿','🥬','🥗','🥦','🥒','🥒'], unlock:10, eventOnly:false },
  { id:'tree_089', name:'Cây Sả', emoji:['🌱','🌿','🫐','🫐','🍇','🍇','🍇'], unlock:11, eventOnly:false },
  { id:'tree_090', name:'Cây Gừng', emoji:['🌱','🌿','🍒','🍒','🍒','🌳','🏞️'], unlock:12, eventOnly:false },
  { id:'tree_091', name:'Cây Nghệ', emoji:['🌱','🌿','🪴','🌳','🌲','🌴','🏞️'], unlock:13, eventOnly:false },
  { id:'tree_092', name:'Cây Riềng', emoji:['🌱','🌿','🪴','🍋','🍊','🍎','🍎'], unlock:14, eventOnly:false },
  { id:'tree_093', name:'Cây Hành', emoji:['🌱','🌿','🌷','🌸','🌺','🌹','💐'], unlock:15, eventOnly:false },
  { id:'tree_094', name:'Cây Tỏi', emoji:['🌵','🌵','🌵','🌵','🌵','🌵','🌵'], unlock:16, eventOnly:false },
  { id:'tree_095', name:'Cây Kiệu', emoji:['🌱','🎋','🎋','🎍','🎍','🎍','🎍'], unlock:17, eventOnly:false },
  { id:'tree_096', name:'Cây Nấm hương', emoji:['🌱','🌿','🌴','🌴','🌴','🏝️','🏝️'], unlock:18, eventOnly:false },
  { id:'tree_097', name:'Cây Nấm mối', emoji:['🍄','🍄','🍄','🍄','🍄','🍄','🍄'], unlock:19, eventOnly:false },
  { id:'tree_098', name:'Cây Dương xỉ', emoji:['🌱','🌿','🥬','🥗','🥦','🥒','🥒'], unlock:20, eventOnly:false },
  { id:'tree_099', name:'Cây Rêu', emoji:['🌱','🌿','🫐','🫐','🍇','🍇','🍇'], unlock:21, eventOnly:false },
  { id:'tree_100', name:'Cây Tảo', emoji:['🌱','🌿','🍒','🍒','🍒','🌳','🏞️'], unlock:22, eventOnly:false },
];

const STAGES = [
  { name:'Hạt giống', min:0 }, { name:'Mầm non', min:1 }, { name:'Cây nhỏ', min:3 },
  { name:'Cây trung', min:7 }, { name:'Cây lớn', min:14 }, { name:'Cây trưởng thành', min:25 },
  { name:'Cây cổ thụ', min:45 }
];

const WEATHERS = [
  { id:'sunny', icon:'☀️' }, { id:'cloudy', icon:'☁️' }, { id:'rain', icon:'🌧️' },
  { id:'hot', icon:'🔥' }, { id:'windy', icon:'💨' }
];

const ACHIEVEMENTS = [
  { id:'first', name:'Lần đầu tưới', desc:'Tưới lần đầu', check:s=>s.totalWater>=1 },
  { id:'streak3', name:'Kiên trì', desc:'Chuỗi 3 ngày', check:s=>s.bestStreak>=3 },
  { id:'streak7', name:'Một tuần', desc:'Chuỗi 7 ngày', check:s=>s.bestStreak>=7 },
  { id:'streak30', name:'Một tháng', desc:'Chuỗi 30 ngày', check:s=>s.bestStreak>=30 },
  { id:'water50', name:'Người làm vườn', desc:'50 lần tưới', check:s=>s.totalWater>=50 },
  { id:'water200', name:'Chuyên gia', desc:'200 lần tưới', check:s=>s.totalWater>=200 },
  { id:'harvest10', name:'Thu hoạch', desc:'Hái 10 quả', check:s=>s.totalFruits>=10 },
  { id:'garden3', name:'Khu vườn', desc:'Trồng 3 cây', check:s=>s.slots.filter(x=>x).length>=3 },
  { id:'allTrees', name:'Sưu tầm', desc:'Mở khóa mọi cây', check:s=>s.unlockedTrees.filter(id=>!TREE_TYPES.find(t=>t.id===id)?.eventOnly).length>=6 },
  { id:'minigame', name:'Tay nhanh', desc:'20 điểm mini-game', check:s=>s.bestMini>=20 },
  { id:'login7', name:'Chăm chỉ', desc:'Đăng nhập 7 ngày', check:s=>s.loginStreak>=7 }
];


const SUPPORT_ITEMS = [
  { id:'fert_pack', name:'Gói phân x5', price:8, fert:5 },
  { id:'fert_big', name:'Gói phân x15', price:20, fert:15 },
  { id:'water_boost', name:'Tăng trưởng +3', price:6, water:3 },
  { id:'water_boost5', name:'Tăng trưởng +8', price:14, water:8 },
  { id:'health_potion', name:'Thuốc hồi máu', price:5, health:100 },
  { id:'streak_shield', name:'Khiên chuỗi 1 ngày', price:25, shield:1 },
  { id:'lucky_seed', name:'Hạt may mắn', price:12, unlockRandom:true },
  { id:'fruit_basket', name:'Giỏ quả x3', price:10, fruits:3 },
  { id:'super_mix', name:'Siêu hỗn hợp', price:30, fert:10, water:5, fruits:5 },
  { id:'rain_charm', name:'Bùa mưa', price:15, weather:'rain' },
];

const POTS = [
  { id:'default', name:'Chậu thường', price:0, class:'' },
  { id:'wood', name:'Chậu gỗ', price:5, class:'pot-wood' },
  { id:'gold', name:'Chậu vàng', price:15, class:'pot-gold' },
  { id:'crystal', name:'Chậu pha lê', price:25, class:'pot-crystal' },
  { id:'clay', name:'Chậu đất nung', price:8, class:'pot-wood' },
  { id:'marble', name:'Chậu đá hoa', price:20, class:'pot-crystal' },
  { id:'neon', name:'Chậu neon', price:30, class:'pot-gold' },
  { id:'bamboo_pot', name:'Chậu tre', price:12, class:'pot-wood' },
];

const THEMES_SHOP = [
  { id:'default', name:'Mặc định', price:0 },
  { id:'sakura', name:'Sakura', price:8 },
  { id:'autumn', name:'Mùa thu', price:8 },
  { id:'winter', name:'Mùa đông', price:8 },
  { id:'night-garden', name:'Vườn đêm', price:12 }
];

const DAILY_REWARDS = [
  { day:1, fert:1, fruits:0 },
  { day:2, fert:1, fruits:1 },
  { day:3, fert:2, fruits:1 },
  { day:4, fert:2, fruits:2 },
  { day:5, fert:3, fruits:2 },
  { day:6, fert:3, fruits:3 },
  { day:7, fert:5, fruits:5 }
];
